feat: show output for deploy preview command
This should help with debugging.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -100,7 +100,11 @@ runs:
         RESULTS=$(npx firebase-tools hosting:channel:deploy $GITHUB_HEAD_REF \
         --expires 3d \
         --project ${{ inputs.project-id }} \
-        --json)
+        --json | tee /dev/tty)
+        if [ $(echo $RESULTS | jq '.status') != 'success' ] then
+          echo "deploy failed"
+          exit 1
+        fi
         echo "::set-output name=url::$(echo $RESULTS | jq --raw-output '.result | .[] | .url')"
         echo "::set-output name=expires::$(echo $RESULTS | jq '.result | .[] | .expireTime')"
 
